### PR TITLE
Add address list when doing equal splits

### LINKED ISSUE #6: Address list when doing equal splits
When adding addresses while making equal splits, we don't have any ENS resolution or cool Address components.  As addresses are added they should resolve the ENS and then display in an Address component above the address entry inputs similar to how it works while splitting unequal amounts.  Maintaining the ability to copy in a list of multiple address/ENS should be retained as that is helpful functionality.

These updates will help the person doing the splitting know they are sending to the right addresses.

### PR DESCRIPTION
**Pull request by YanVictorSN**
## Description

Add address list when doing equal splits.

https://github.com/BuidlGuidl/Eth-Splitter/assets/98413246/484ffe0b-b05b-44b8-8fe7-e4a85a9098ab

## Additional Information

- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues
Closes #6

Your ENS/address: yanvictorsn.eth

### CODE REVIEW

**Comment by ZakGriffith** [comment]
This is coming along great!  Some other features that would be great here are:

- [ ] Ability to enter an ENS into the Recipient Wallets section and it appears up top in the Addresses section.  The same way that entering an address does currently.

- [ ] When an address/ENS is entered into the Recipient Wallet section, it is currently added to the top Addresses section.  This should also remove it from the Recipient Wallet section, and add a (Trash Can Icon) next to it up in the Addresses section to remove it from the splits.

**Comment by YanVictorSN** [comment]
## Description

Add getENSName function to handle ENS, add (Trash Can Icon) to remove from splits and remove addresses from Recipient Wallet section.

https://github.com/BuidlGuidl/Eth-Splitter/assets/98413246/6626da69-0038-468b-8a78-643a244213d2

## Additional Information

- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

- [x] Ability to enter an ENS into the Recipient Wallets section and it appears up top in the Addresses section. The same way that entering an address does currently.

- [x] When an address/ENS is entered into the Recipient Wallet section, it is currently added to the top Addresses section. This should also remove it from the Recipient Wallet section, and add a (Trash Can Icon) next to it up in the Addresses section to remove it from the splits.

- [x] Able to handle ENS and 0x Adresses together.

## Related Issues
Closes #6

Your ENS/address: yanvictorsn.eth

**Comment by ZakGriffith** [comment]
Looks like the latest updates introduced a bug when trying to type in an ENS.  The input get's cleared.

clearingText

**Comment by YanVictorSN** [comment]
Oh. Forgot to test that. Gonna fix it. Thanks for the review.

**Comment by YanVictorSN** [comment]
## Description

Refactored the addMultipleAddress function, added wallets Reducer to handle wallet insertion and removal, and added debounce to handle multiple calls.

## Additional Information

- [x] Fix input bug clear.
- [x] Refactor addMultipleAddress.
- [x] Add Debouncer function.
- [x] Change useState to useReducer.

## Related Issues
Closes #6

Your ENS/address: yanvictorsn.eth

**Pull request merged**
